.\python.exe -m pip uninstall astunparse -y
.\python.exe -m pip uninstall bitarray -y
.\python.exe -m pip uninstall cachetools -y
.\python.exe -m pip uninstall certifi -y
.\python.exe -m pip uninstall cffi -y
.\python.exe -m pip uninstall chardet -y
.\python.exe -m pip uninstall click -y
.\python.exe -m pip uninstall ctranslate2 -y
.\python.exe -m pip uninstall cycler -y
.\python.exe -m pip uninstall Cython -y
.\python.exe -m pip uninstall Flask -y
.\python.exe -m pip uninstall Flask-Cors -y
.\python.exe -m pip uninstall gast -y
.\python.exe -m pip uninstall google-auth -y
.\python.exe -m pip uninstall google-auth-oauthlib -y
.\python.exe -m pip uninstall google-pasta -y
.\python.exe -m pip uninstall grpcio -y
.\python.exe -m pip uninstall h5py -y
.\python.exe -m pip uninstall hydra-core -y
.\python.exe -m pip uninstall idna -y
.\python.exe -m pip uninstall importlib-resources -y
.\python.exe -m pip uninstall itsdangerous -y
.\python.exe -m pip uninstall Jinja2 -y
.\python.exe -m pip uninstall Keras -y
.\python.exe -m pip uninstall Keras-Preprocessing -y
.\python.exe -m pip uninstall kiwisolver -y
.\python.exe -m pip uninstall Markdown -y
.\python.exe -m pip uninstall MarkupSafe -y
.\python.exe -m pip uninstall matplotlib -y
.\python.exe -m pip uninstall mss -y
.\python.exe -m pip uninstall numpy -y
.\python.exe -m pip uninstall oauthlib -y
.\python.exe -m pip uninstall omegaconf -y
.\python.exe -m pip uninstall opencv-python -y
.\python.exe -m pip uninstall opt-einsum -y
.\python.exe -m pip uninstall pandas -y
.\python.exe -m pip uninstall Pillow -y
.\python.exe -m pip uninstall portalocker -y
.\python.exe -m pip uninstall protobuf -y
.\python.exe -m pip uninstall pyasn1 -y
.\python.exe -m pip uninstall pyasn1-modules -y
.\python.exe -m pip uninstall pycparser -y
.\python.exe -m pip uninstall pyparsing -y
.\python.exe -m pip uninstall python-dateutil -y
.\python.exe -m pip uninstall python-dotenv -y
.\python.exe -m pip uninstall pytz -y
.\python.exe -m pip uninstall pywin32 -y
.\python.exe -m pip uninstall PyYAML -y
.\python.exe -m pip uninstall regex -y
.\python.exe -m pip uninstall requests -y
.\python.exe -m pip uninstall requests-oauthlib -y
.\python.exe -m pip uninstall rsa -y
.\python.exe -m pip uninstall sacrebleu -y
.\python.exe -m pip uninstall scipy -y
.\python.exe -m pip uninstall sentencepiece -y
.\python.exe -m pip uninstall six -y
.\python.exe -m pip uninstall tensorboard -y
.\python.exe -m pip uninstall tensorboard-plugin-wit -y
.\python.exe -m pip uninstall tensorflow-estimator -y
.\python.exe -m pip uninstall termcolor -y
.\python.exe -m pip uninstall torch -y
.\python.exe -m pip uninstall torchaudio -y
.\python.exe -m pip uninstall torchsummary -y
.\python.exe -m pip uninstall torchvision -y
.\python.exe -m pip uninstall tqdm -y
.\python.exe -m pip uninstall typing-extensions -y
.\python.exe -m pip uninstall urllib3 -y
.\python.exe -m pip uninstall Werkzeug -y
.\python.exe -m pip uninstall wrapt -y
